### ISSUE TITLE
Build pages for specific routes (from user config)

### ISSUE THREAD

**Issue by fvsch** [fvsch/kirby-staticbuilder#11]
Similarly to how the `'plugin.staticbuilder.assets'` config allows listing files and folders to copy, we might have a `'plugin.staticbuilder.routes'` array for routes that should be rendered.

Example implementation by @mogelbrod:
https://github.com/mogelbrod/kirby-staticbuilder/commit/bfe8605aa295a95dd5f64282738955e7183b7540

**Comment by mogelbrod** [comment]
The example implementation `buildRoute` is currently a bit too heavy on the copy-paste from `buildPage`. Parts of their implementation should probably be extracted into helper functions. It has also only been tested with a route whose action is `tpl::load(...);` and might not work for all types of routes.

I was a bit conflicted regarding the option name; personal preference says `routes` but `additionalRoutes` avoids any confusion that it might specify exactly which routes (including pages) which should be built. `routes` fits in better for all intents and purposes however.

**Comment by fvsch** [comment]
It's bikeshedding, but the rationale for the shorter `route` versus `additionalRoutes` is that in the context of the plugin just `route` should be clear enough, and also Kirby itself tends to use short nouns (at the cost of being a bit ambiguous sometimes) instead of noun+verb or adjective+noun forms. So for the public-facing parts (config mostly), I'd like to follow that lead.

**Comment by mogelbrod** [comment]
Being able to specify additional route sources pointing to page structure fields could also be really neat.

**Comment by fvsch** [comment]
Not sure what you mean. Could you give an example?

**Comment by fvsch** [comment]
I’ll probably go for a 1.0 release without this feature, and try to add it in a 1.1 release.

**Comment by mogelbrod** [comment]
My use case was to be able to automatically build routes created by the [redirecty plugin](https://github.com/ivinteractive/kirbycms-redirects). A better alternative would be to query the kirby router for all GET routes and build these though. I'll look into doing this asap.

Planning this for v1.1 sounds fair.

**Comment by mogelbrod** [comment]
I just finished adding functionality that allows the plugin to build all/specified GET routes known to the Kirby router. A sensible default would in my opinion be to build all GET routes that doesn't contain parameters.

[My implementation](mogelbrod/kirby-staticbuilder@b80c83229a8dda4468eac9448d4ef63fa608d9ca) adds the following:

`plugin.staticbuilder.routes`: Array of URIs to build, with the following syntax:
- `*` - all routes
- `page/id` - exact URI
- `string*` - all defined routes that begin with `string`
- `some/blog/tag:{tags}` - expands `{tags}` into a route for each `tags` value in all visible subpages of `some/blog` (can be further developed to support other expansions)

`plugin.staticbuilder.excluderoutes`: Array of URIs to avoid building, supports 'string*' syntax as well.

I also built a [simple redirects plugin](https://gist.github.com/mogelbrod/5e5c64ff943ba6909ce3bd35a57bc808) which works with this functionality to build redirecting html files.

**Comment by prookie** [comment]
Hi,

is this feature still under consideration?
I would love to use it for sitemaps etc. in my projects.

**Comment by mogelbrod** [comment]
@prookie: [My fork](https://github.com/mogelbrod/kirby-staticbuilder) is up to date and still supports it until it gets added to upstream.

**Comment by fvsch** [comment]
Hi @prookie. I’m not considering this feature or any new feature for this project, since I’m not using it anymore and don't have clients who do. As such I’m going to close all feature requests, not because they’re bad ideas but because they’re unlikely to happen.
