### ISSUE TITLE
Url broken in the readme

### ISSUE THREAD

**Issue by ingvoo** [fvsch/kirby-staticbuilder#19]
The url to the documentation for how to enable the plugin is broken: https://github.com/fvsch/kirby-staticbuilder/blob/master/doc/config.md

**Comment by ingvoo** [comment]
I assume it should be this one: https://github.com/fvsch/kirby-staticbuilder/blob/master/doc/options.md

**Comment by fvsch** [comment]
Thanks for the heads up.
