### ISSUE TITLE
All pages has startpage content

### ISSUE THREAD

**Issue by jonasedemalm** [fvsch/kirby-staticbuilder#25]
The builder used to work great but now it outputs the startpage content to all pages, except error.html which is as expected.

I tried updating to the latest version but still no luck.

I have a super simple site and i run with default options

**Comment by jonasedemalm** [comment]
Not sure what i did, but not it works again ;)

**Comment by tobiasfabian** [comment]
Maybe you activated caching (`c::set('cache', true);`) => does not work
and later unset the cache => works again.

I made a pull request to fix this problem.

**Comment by fvsch** [comment]
PR is https://github.com/fvsch/kirby-staticbuilder/pull/28
