### ISSUE TITLE
Do without content folder entirely in static site

### ISSUE THREAD

**Issue by shoesforindustry** [fvsch/kirby-staticbuilder#33]
Maybe worth mentioning in the docs?

That if you only use images via thumb/resize and that you pre-generate them with the [Kirby ImageKit Plugin](https://github.com/fabianmichael/kirby-imagekit), you probably do not need to include the `content` folder in your static website output?

**Comment by fvsch** [comment]
Or even when resizing (or just copying as-is) with the built-in thumb API.
But I'm not sure where it would fit in the docs, which are already quite long. Any suggestions?

**Comment by shoesforindustry** [comment]
I think I would put it in the static.md, it would seen to fit there.

**Comment by shoesforindustry** [comment]
Florens, also is there a way to exclude files when using staticbuilder.assets?  I know how to do it with files, but I want to exclude the `filename.jpg-imagekitjob.php` which the imagekit plugin  creates in the thumbs folder, which is copied with staticbuilder.assets.

**Comment by fvsch** [comment]
Nope.

**Comment by shoesforindustry** [comment]
No worries, I'm running a post (static builder) build anyway for sitemap, robots.txt and publishing to github, so I can probably do it before that.

**Comment by fvsch** [comment]
Closing feature requests as described in #40.
