### ISSUE TITLE
Panel Dashboard Widget

### ISSUE THREAD

**Issue by zvaehn** [fvsch/kirby-staticbuilder#37]
How about a little Dashboard widget which shows some meta-information and give the panel-user a link to the staticbuilder-page?

**Comment by fvsch** [comment]
That's a good idea, but with the current implementation it would be a bit hard to do (or very hacky).

In the future I’d like to change the technical implementation to be split between a JSON API and small JS clients (the /staticbuilder/ page could be one client, and the dashboard widget another one).

**Comment by zvaehn** [comment]
Yep! I took a look in the code to see if i can make the widget on my own, but its really focussed on the table-generation for this one specific page.

Currently my little widget looks like this: 
<img width="431" alt="screenshot" src="https://user-images.githubusercontent.com/5555821/42805728-dfa1d150-89ac-11e8-9b65-7451e82bad7c.png">

Looking forward to see your suggested changes :)

**Comment by fvsch** [comment]
Closing feature requests as described in #40.
