### ISSUE TITLE
Option to manually sync the assets?

### ISSUE THREAD

**Issue by zvaehn** [fvsch/kirby-staticbuilder#38]

**Comment by fvsch** [comment]
I’m not sure what you mean. Can you elaborate?

**Comment by zvaehn** [comment]
Sometimes there might be the use-case that you dont want to rebuild all pages, but want to deploy updated assets (like css changes) to the static-page. Currently this can only be done manually from a 3rd party instance like ftp/ssh.

**Comment by fvsch** [comment]
Closing feature requests as described in #40.
